name: Manual Release
'on':
  workflow_dispatch:
    inputs:
      version:
        description: "Release Version"
        required: true

jobs:
  build:
    env:
      GOOS: linux
      GOARCH: amd64
    runs-on: ubuntu-latest
    steps:
      - name: "Fetch source code"
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install Go toolchain
        uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5.3.0
        with:
          go-version-file: 'go.mod'

      - name: "Build tofu executable"
        run: |
          go build ./cmd/tofu

      - name: Tag Release
        uses: mathieudutour/github-tag-action@v6.1
        continue-on-error: true
        with:
          custom_tag: ${{ inputs.version }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        continue-on-error: true
        with:
          tag_name: ${{ inputs.version }}
          files: tofu